### ISSUE TITLE
Flat notes' aliases

### ISSUE THREAD

**Issue by laquazi** [paranim/paramidi#3]
Could be really helpful having aliases for flat notes and not convert them to their sharp equivalents every time.

**Comment by oakes** [comment]
Yeah that is doable. I can define constants that point to the equivalent sharp note. The only difficult thing is deciding on what character to use to represent flat...

**Comment by oakes** [comment]
Check out this commit https://github.com/paranim/paramidi/commit/63f2258fd04735cb5e066a01b76367c1d12c7bb2

I added constants that use the correct unicode symbols for sharps and flats. Not necessarily easy to type but i figure if you're committed you can figure out a keyboard shortcut or something. What do you think?

**Comment by oakes** [comment]
I just realized i can do this entirely using source filters....check it out:

https://github.com/paranim/paramidi/commit/3ce7cce43c5d6e4e59f6a4b934fe57d4e8754310

**Comment by laquazi** [comment]
I didn't know about SCFs before 3ce7cce43c5d6e4e59f6a4b934fe57d4e8754310, so thank you, works for me!
